/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

/**
 * @summary Get all products
 */
export const getProductsResponseItem = zod.object({
  id: zod.uuid().describe('The unique identifier for the product'),
  name: zod.string().describe('The name of the product'),
  description: zod.string().describe('The description of the product'),
  price: zod.number().describe('The price of the product'),
  status: zod.enum(['active', 'inactive', 'pending']).describe('The status of the product'),
  category: zod.string().describe('The category of the product'),
  image: zod.string().describe('The image of the product'),
  stock: zod.number().describe('The stock of the product'),
  brand: zod.string().describe('The brand of the product'),
  tags: zod.array(zod.string()).describe('The tags of the product'),
  attributes: zod.object({
    color: zod.string().optional().describe('The color of the product'),
    size: zod.string().optional().describe('The size of the product'),
    weight: zod.number().optional().describe('The weight of the product'),
    dimensions: zod
      .object({
        length: zod.number().optional(),
        width: zod.number().optional(),
        height: zod.number().optional(),
      })
      .optional(),
  }),
  createdAt: zod.iso.datetime({}).describe('The date and time the product was created'),
})
export const getProductsResponse = zod.array(getProductsResponseItem)
