/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

/**
 * @summary Get all tasks
 */
export const getTasksResponseProgressPercentMin = 0

export const getTasksResponseProgressPercentMax = 100

export const getTasksResponseItem = zod.object({
  id: zod.uuid().describe('The unique identifier for the task'),
  title: zod.string().describe('The title of the task'),
  progress_percent: zod
    .number()
    .min(getTasksResponseProgressPercentMin)
    .max(getTasksResponseProgressPercentMax)
    .describe('The progress percentage of the task'),
  description: zod.string().describe('The description of the task'),
  status: zod
    .enum(['Pending', 'In Progress', 'Cancelled', 'Backlog', 'Todo', 'In Review', 'Completed'])
    .describe('The status of the task'),
  category: zod.object({
    id: zod.uuid().describe('The unique identifier for the task category'),
    name: zod.string().describe('The name of the task category'),
  }),
  priority: zod.enum(['Low', 'Medium', 'High']).describe('The priority of the task'),
  due_date: zod.iso.datetime({}).describe('The due date of the task'),
  created_at: zod.iso.datetime({}).describe('The date and time the task was created'),
  updated_at: zod.iso.datetime({}).describe('The date and time the task was updated'),
})
export const getTasksResponse = zod.array(getTasksResponseItem)

/**
 * @summary Get all task categories
 */
export const getTasksCategoryResponseItem = zod.object({
  id: zod.uuid().describe('The unique identifier for the task category'),
  name: zod.string().describe('The name of the task category'),
})
export const getTasksCategoryResponse = zod.array(getTasksCategoryResponseItem)

/**
 * @summary Get a task by ID
 */
export const getTasksIdParams = zod.object({
  id: zod.uuid().describe('Task ID'),
})

export const getTasksIdResponseProgressPercentMin = 0

export const getTasksIdResponseProgressPercentMax = 100

export const getTasksIdResponse = zod.object({
  id: zod.uuid().describe('The unique identifier for the task'),
  title: zod.string().describe('The title of the task'),
  progress_percent: zod
    .number()
    .min(getTasksIdResponseProgressPercentMin)
    .max(getTasksIdResponseProgressPercentMax)
    .describe('The progress percentage of the task'),
  description: zod.string().describe('The description of the task'),
  status: zod
    .enum(['Pending', 'In Progress', 'Cancelled', 'Backlog', 'Todo', 'In Review', 'Completed'])
    .describe('The status of the task'),
  category: zod.object({
    id: zod.uuid().describe('The unique identifier for the task category'),
    name: zod.string().describe('The name of the task category'),
  }),
  priority: zod.enum(['Low', 'Medium', 'High']).describe('The priority of the task'),
  due_date: zod.iso.datetime({}).describe('The due date of the task'),
  created_at: zod.iso.datetime({}).describe('The date and time the task was created'),
  updated_at: zod.iso.datetime({}).describe('The date and time the task was updated'),
})
