/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */

export type PostLogin200 = {
  /** The access token */
  access_token: string
  /** The refresh token */
  refresh_token: string
}
