/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */

export type PostLoginBody = {
  /** The user's email address */
  email: string
  /** The user's password */
  password: string
}
