/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */
import type { ProductStatus } from './productStatus'
import type { ProductAttributes } from './productAttributes'

export interface Product {
  /** The unique identifier for the product */
  id: string
  /** The name of the product */
  name: string
  /** The description of the product */
  description: string
  /** The price of the product */
  price: number
  /** The status of the product */
  status: ProductStatus
  /** The category of the product */
  category: string
  /** The image of the product */
  image: string
  /** The stock of the product */
  stock: number
  /** The brand of the product */
  brand: string
  /** The tags of the product */
  tags: string[]
  attributes: ProductAttributes
  /** The date and time the product was created */
  createdAt: string
}
