/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */
import type { ProductAttributesDimensions } from './productAttributesDimensions'

export type ProductAttributes = {
  /** The color of the product */
  color?: string
  /** The size of the product */
  size?: string
  /** The weight of the product */
  weight?: number
  dimensions?: ProductAttributesDimensions
}
