/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The priority of the task
 */
export type TaskPriority = (typeof TaskPriority)[keyof typeof TaskPriority]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskPriority = {
  Low: 'Low',
  Medium: 'Medium',
  High: 'High',
} as const
