/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */
import type { TaskStatus } from './taskStatus'
import type { TaskCategory } from './taskCategory'
import type { TaskPriority } from './taskPriority'

export interface Task {
  /** The unique identifier for the task */
  id: string
  /** The title of the task */
  title: string
  /**
   * The progress percentage of the task
   * @minimum 0
   * @maximum 100
   */
  progress_percent: number
  /** The description of the task */
  description: string
  /** The status of the task */
  status: TaskStatus
  category: TaskCategory
  /** The priority of the task */
  priority: TaskPriority
  /** The due date of the task */
  due_date: string
  /** The date and time the task was created */
  created_at: string
  /** The date and time the task was updated */
  updated_at: string
}
