/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The status of the task
 */
export type TaskStatus = (typeof TaskStatus)[keyof typeof TaskStatus]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TaskStatus = {
  Pending: 'Pending',
  In_Progress: 'In Progress',
  Cancelled: 'Cancelled',
  Backlog: 'Backlog',
  Todo: 'Todo',
  In_Review: 'In Review',
  Completed: 'Completed',
} as const
