/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */

export interface TaskCategory {
  /** The unique identifier for the task category */
  id?: string
  /** The name of the task category */
  name?: string
}
