/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */
import type { UserAddress } from './userAddress'
import type { UserGender } from './userGender'
import type { UserRole } from './userRole'
import type { UserStatus } from './userStatus'

export interface User {
  /** The unique identifier for the user */
  id?: string
  /** The name of the user */
  name?: string
  /** The email address of the user */
  email?: string
  address?: UserAddress
  /** The phone number of the user */
  phone?: string
  /** The website of the user */
  website?: string
  /** The gender of the user */
  gender?: UserGender
  /** The role of the user */
  role?: UserRole
  /** The status of the user */
  status?: UserStatus
  /** The date and time the user was created */
  createdAt?: string
}
