/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */
import type { UserRolesRole } from './userRolesRole'

export interface UserRoles {
  /** The role of the user */
  role: UserRolesRole
  /** The permissions groups of the user */
  permissions_groups: string[]
  /** The permissions of the user */
  permissions: string[]
}
