/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The gender of the user
 */
export type UserGender = (typeof UserGender)[keyof typeof UserGender]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserGender = {
  male: 'male',
  female: 'female',
  other: 'other',
} as const
