/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */

/**
 * The role of the user
 */
export type UserRolesRole = (typeof UserRolesRole)[keyof typeof UserRolesRole]

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRolesRole = {
  user: 'user',
  admin: 'admin',
  superadmin: 'superadmin',
  sale: 'sale',
  marketing: 'marketing',
} as const
