/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */

export type UserAddress = {
  /** The street of the user */
  street?: string
  /** The city of the user */
  city?: string
  /** The state of the user */
  state?: string
  /** The zip code of the user */
  zip?: string
  /** The country of the user */
  country?: string
}
