/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

/**
 * @summary Login
 */
export const postLoginBody = zod.object({
  email: zod.email().describe("The user's email address"),
  password: zod.describe("The user's password"),
})

export const postLoginResponse = zod.object({
  token: zod.string().optional(),
})
