/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */
import { useQuery } from '@tanstack/vue-query'
import type {
  DataTag,
  QueryClient,
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryReturnType,
} from '@tanstack/vue-query'

import { computed, unref } from 'vue'
import type { MaybeRef } from 'vue'

import type { GetTasksId404, Task, TaskCategory } from '../../models'

import { request } from '../../../../lib/axios/index'

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1]

/**
 * @summary Get all tasks
 */
export const getTasks = (options?: SecondParameter<typeof request>, signal?: AbortSignal) => {
  return request<Task[]>({ url: `/tasks`, method: 'GET', signal }, options)
}

export const getGetTasksQueryKey = () => {
  return ['tasks'] as const
}

export const getGetTasksQueryOptions = <TData = Awaited<ReturnType<typeof getTasks>>, TError = unknown>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>>
  request?: SecondParameter<typeof request>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getGetTasksQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTasks>>> = ({ signal }) => getTasks(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>
}

export type GetTasksQueryResult = NonNullable<Awaited<ReturnType<typeof getTasks>>>
export type GetTasksQueryError = unknown

/**
 * @summary Get all tasks
 */

export function useGetTasks<TData = Awaited<ReturnType<typeof getTasks>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasks>>, TError, TData>>
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTasksQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Get all task categories
 */
export const getTasksCategory = (options?: SecondParameter<typeof request>, signal?: AbortSignal) => {
  return request<TaskCategory[]>({ url: `/tasks/category`, method: 'GET', signal }, options)
}

export const getGetTasksCategoryQueryKey = () => {
  return ['tasks', 'category'] as const
}

export const getGetTasksCategoryQueryOptions = <
  TData = Awaited<ReturnType<typeof getTasksCategory>>,
  TError = unknown,
>(options?: {
  query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksCategory>>, TError, TData>>
  request?: SecondParameter<typeof request>
}) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getGetTasksCategoryQueryKey()

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTasksCategory>>> = ({ signal }) =>
    getTasksCategory(requestOptions, signal)

  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTasksCategory>>,
    TError,
    TData
  >
}

export type GetTasksCategoryQueryResult = NonNullable<Awaited<ReturnType<typeof getTasksCategory>>>
export type GetTasksCategoryQueryError = unknown

/**
 * @summary Get all task categories
 */

export function useGetTasksCategory<TData = Awaited<ReturnType<typeof getTasksCategory>>, TError = unknown>(
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksCategory>>, TError, TData>>
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTasksCategoryQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}

/**
 * @summary Get a task by ID
 */
export const getTasksId = (
  id: MaybeRef<string | undefined | null>,
  options?: SecondParameter<typeof request>,
  signal?: AbortSignal,
) => {
  id = unref(id)

  return request<Task>({ url: `/tasks/${id}`, method: 'GET', signal }, options)
}

export const getGetTasksIdQueryKey = (id: MaybeRef<string | undefined | null>) => {
  return ['tasks', id] as const
}

export const getGetTasksIdQueryOptions = <TData = Awaited<ReturnType<typeof getTasksId>>, TError = GetTasksId404>(
  id: MaybeRef<string | undefined | null>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksId>>, TError, TData>>
    request?: SecondParameter<typeof request>
  },
) => {
  const { query: queryOptions, request: requestOptions } = options ?? {}

  const queryKey = getGetTasksIdQueryKey(id)

  const queryFn: QueryFunction<Awaited<ReturnType<typeof getTasksId>>> = ({ signal }) =>
    getTasksId(id, requestOptions, signal)

  return { queryKey, queryFn, enabled: computed(() => !!unref(id)), ...queryOptions } as UseQueryOptions<
    Awaited<ReturnType<typeof getTasksId>>,
    TError,
    TData
  >
}

export type GetTasksIdQueryResult = NonNullable<Awaited<ReturnType<typeof getTasksId>>>
export type GetTasksIdQueryError = GetTasksId404

/**
 * @summary Get a task by ID
 */

export function useGetTasksId<TData = Awaited<ReturnType<typeof getTasksId>>, TError = GetTasksId404>(
  id: MaybeRef<string | undefined | null>,
  options?: {
    query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasksId>>, TError, TData>>
    request?: SecondParameter<typeof request>
  },
  queryClient?: QueryClient,
): UseQueryReturnType<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetTasksIdQueryOptions(id, options)

  const query = useQuery(queryOptions, queryClient) as UseQueryReturnType<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>
  }

  query.queryKey = unref(queryOptions).queryKey as DataTag<QueryKey, TData, TError>

  return query
}
