/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */
import { faker } from '@faker-js/faker'

import { HttpResponse, delay, http } from 'msw'

import type { GetTasksId404, Task, TaskCategory } from '../../models'

export const getGetTasksResponseMock = (): Task[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.string.uuid(),
    title: faker.string.alpha({ length: { min: 10, max: 20 } }),
    progress_percent: faker.helpers.arrayElement([
      faker.number.float({ min: 0, max: 100, fractionDigits: 2 }),
      undefined,
    ]),
    description: faker.string.alpha({ length: { min: 10, max: 20 } }),
    status: faker.helpers.arrayElement([
      'Pending',
      'In Progress',
      'Cancelled',
      'Backlog',
      'Todo',
      'In Review',
      'Completed',
    ] as const),
    category: {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    },
    priority: faker.helpers.arrayElement(['Low', 'Medium', 'High'] as const),
    dueDate: `${faker.date.past().toISOString().split('.')[0]}Z`,
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  }))

export const getGetTasksResponseMock200 = (): Task[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.string.uuid(),
    title: faker.string.alpha({ length: { min: 10, max: 20 } }),
    progress_percent: faker.helpers.arrayElement([
      faker.number.float({ min: 0, max: 100, fractionDigits: 2 }),
      undefined,
    ]),
    description: faker.string.alpha({ length: { min: 10, max: 20 } }),
    status: faker.helpers.arrayElement([
      'Pending',
      'In Progress',
      'Cancelled',
      'Backlog',
      'Todo',
      'In Review',
      'Completed',
    ] as const),
    category: {
      id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
      name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
    },
    priority: faker.helpers.arrayElement(['Low', 'Medium', 'High'] as const),
    dueDate: `${faker.date.past().toISOString().split('.')[0]}Z`,
    createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
    updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  }))

export const getGetTasksCategoryResponseMock = (): TaskCategory[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  }))

export const getGetTasksCategoryResponseMock200 = (): TaskCategory[] =>
  Array.from({ length: faker.number.int({ min: 1, max: 10 }) }, (_, i) => i + 1).map(() => ({
    id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  }))

export const getGetTasksIdResponseMock = (overrideResponse: Partial<Task> = {}): Task => ({
  id: faker.string.uuid(),
  title: faker.string.alpha({ length: { min: 10, max: 20 } }),
  progress_percent: faker.helpers.arrayElement([
    faker.number.float({ min: 0, max: 100, fractionDigits: 2 }),
    undefined,
  ]),
  description: faker.string.alpha({ length: { min: 10, max: 20 } }),
  status: faker.helpers.arrayElement([
    'Pending',
    'In Progress',
    'Cancelled',
    'Backlog',
    'Todo',
    'In Review',
    'Completed',
  ] as const),
  category: {
    id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  },
  priority: faker.helpers.arrayElement(['Low', 'Medium', 'High'] as const),
  dueDate: `${faker.date.past().toISOString().split('.')[0]}Z`,
  createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  ...overrideResponse,
})

export const getGetTasksIdResponseMock200 = (overrideResponse: Partial<Task> = {}): Task => ({
  id: faker.string.uuid(),
  title: faker.string.alpha({ length: { min: 10, max: 20 } }),
  progress_percent: faker.helpers.arrayElement([
    faker.number.float({ min: 0, max: 100, fractionDigits: 2 }),
    undefined,
  ]),
  description: faker.string.alpha({ length: { min: 10, max: 20 } }),
  status: faker.helpers.arrayElement([
    'Pending',
    'In Progress',
    'Cancelled',
    'Backlog',
    'Todo',
    'In Review',
    'Completed',
  ] as const),
  category: {
    id: faker.helpers.arrayElement([faker.string.uuid(), undefined]),
    name: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  },
  priority: faker.helpers.arrayElement(['Low', 'Medium', 'High'] as const),
  dueDate: `${faker.date.past().toISOString().split('.')[0]}Z`,
  createdAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  updatedAt: `${faker.date.past().toISOString().split('.')[0]}Z`,
  ...overrideResponse,
})

export const getGetTasksIdResponseMock404 = (overrideResponse: Partial<GetTasksId404> = {}): GetTasksId404 => ({
  message: faker.helpers.arrayElement([faker.string.alpha({ length: { min: 10, max: 20 } }), undefined]),
  ...overrideResponse,
})

export const getGetTasksMockHandler = (
  overrideResponse?: Task[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Task[]> | Task[]),
) => {
  return http.get('*/tasks', async info => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetTasksResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getGetTasksMockHandler200 = (
  overrideResponse?: Task[] | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Task[]> | Task[]),
) => {
  return http.get('*/tasks', async info => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetTasksResponseMock200(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getGetTasksCategoryMockHandler = (
  overrideResponse?:
    | TaskCategory[]
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TaskCategory[]> | TaskCategory[]),
) => {
  return http.get('*/tasks/category', async info => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetTasksCategoryResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getGetTasksCategoryMockHandler200 = (
  overrideResponse?:
    | TaskCategory[]
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<TaskCategory[]> | TaskCategory[]),
) => {
  return http.get('*/tasks/category', async info => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetTasksCategoryResponseMock200(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getGetTasksIdMockHandler = (
  overrideResponse?: Task | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Task> | Task),
) => {
  return http.get('*/tasks/:id', async info => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetTasksIdResponseMock(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getGetTasksIdMockHandler200 = (
  overrideResponse?: Task | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<Task> | Task),
) => {
  return http.get('*/tasks/:id', async info => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetTasksIdResponseMock200(),
      ),
      { status: 200, headers: { 'Content-Type': 'application/json' } },
    )
  })
}

export const getGetTasksIdMockHandler404 = (
  overrideResponse?:
    | GetTasksId404
    | ((info: Parameters<Parameters<typeof http.get>[1]>[0]) => Promise<GetTasksId404> | GetTasksId404),
) => {
  return http.get('*/tasks/:id', async info => {
    await delay(1000)

    return new HttpResponse(
      JSON.stringify(
        overrideResponse !== undefined
          ? typeof overrideResponse === 'function'
            ? await overrideResponse(info)
            : overrideResponse
          : getGetTasksIdResponseMock404(),
      ),
      { status: 404, headers: { 'Content-Type': 'application/json' } },
    )
  })
}
export const getTasksMock = () => [
  getGetTasksMockHandler(),
  getGetTasksCategoryMockHandler(),
  getGetTasksIdMockHandler(),
]
