/**
 * Generated by orval v7.10.0 🍺
 * Do not edit manually.
 * Admin Simple API
 * OpenAPI spec version: 1.0.0
 */
import { z as zod } from 'zod'

/**
 * @summary Get current user
 */
export const getMeResponse = zod.object({
  id: zod.uuid().optional().describe('The unique identifier for the user'),
  name: zod.string().optional().describe('The name of the user'),
  email: zod.email().optional().describe('The email address of the user'),
  address: zod
    .object({
      street: zod.string().optional().describe('The street of the user'),
      city: zod.string().optional().describe('The city of the user'),
      state: zod.string().optional().describe('The state of the user'),
      zip: zod.string().optional().describe('The zip code of the user'),
      country: zod.string().optional().describe('The country of the user'),
    })
    .optional(),
  phone: zod.string().optional().describe('The phone number of the user'),
  website: zod.string().optional().describe('The website of the user'),
  gender: zod.enum(['male', 'female', 'other']).optional().describe('The gender of the user'),
  role: zod.enum(['admin', 'user']).optional().describe('The role of the user'),
  status: zod.enum(['active', 'inactive', 'pending']).optional().describe('The status of the user'),
  createdAt: zod.iso.datetime({}).optional().describe('The date and time the user was created'),
})
